### ISSUE TITLE
Trusted Domain error

### ISSUE THREAD

**Issue by powerriegel** [AykutCevik/owncloud-fail2ban#1]
Hello,

it would be nice to add another thing to the filter. My Owncloud is only accessble via domain. Every day at 2 am there seems to be a IP scanner. It accesses my Owncloud via IP, This throws an excepttion "Trusted domain error" would it be possible to ban them, too?

**Comment by AykutCevik** [comment]
Hi powerriegel,

maybe you can change your default server to avoid accessing the owncloud service by your IP. Is this an option for you?

Otherwise you could create a regular expression for fail2ban, which listens on your "trusted domain errors".

**Comment by powerriegel** [comment]
I've tried this multiple times but it did not work. It seems this does not work with SSL/443. 

Yes, that would be the only one solution but the logs change often and that's why I asked if you could add such an regex here.

**Comment by AykutCevik** [comment]
Since this isn't a login/security issue, which should be handled by this fail2ban-filter, I'm closing this as unrelated.

But take a look at these posts, maybe they will help you:
- https://forum.owncloud.org/viewtopic.php?t=34215
- https://forum.owncloud.org/viewtopic.php?f=38&t=34229
